swagger: "2.0"
info:
  description: "This is a simple swagger for Techy API described here: https://techy-api.vercel.app. The app uses another api endpoint (picsum), but it just returns a random image so I found it unnecessary to create a swagger for it."
  version: "1.0.0"
  title: "TechWiser"
  termsOfService: ""
  contact:
    email: "pattantyus.gerg@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "techy-api.vercel.app"
basePath: "/api"
tags:
  - name: "Techy"
    description: "Everything about tech realted messages."
schemes:
  - "https"
paths:
  /json:
    get:
      tags:
        - "Techy"
      summary: "Get tech related messages"
      description: "Get random tehc related messages"
      operationId: ""
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/TechMessage"
definitions:
  TechMessage:
    type: "object"
    properties:
      message:
        type: "string"
        description: "Tech related sentence"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"